<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-10-05T22:40:34 EDT" name="Suite" finished-at="2021-10-05T22:40:53 EDT" duration-ms="18591">
    <groups>
    </groups>
    <test started-at="2021-10-05T22:40:34 EDT" name="Test" finished-at="2021-10-05T22:40:53 EDT" duration-ms="18591">
      <class name="framework.RediffTest">
        <test-method signature="rediffTester(java.lang.String,java.lang.String)[pri:0, instance:framework.RediffTest@55a561cf]" started-at="2021-10-05T22:40:37 EDT" name="rediffTester" data-provider="getLoginInfo" finished-at="2021-10-05T22:40:43 EDT" duration-ms="6108" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[hello@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[abcdef]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- rediffTester -->
        <test-method signature="rediffTester(java.lang.String,java.lang.String)[pri:0, instance:framework.RediffTest@55a561cf]" started-at="2021-10-05T22:40:43 EDT" name="rediffTester" data-provider="getLoginInfo" finished-at="2021-10-05T22:40:52 EDT" duration-ms="8577" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[john@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[123456]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- rediffTester -->
      </class> <!-- framework.RediffTest -->
      <class name="framework.Validator">
        <test-method is-config="true" signature="initialize()[pri:0, instance:framework.Validator@6b4a4e18]" started-at="2021-10-05T22:40:34 EDT" name="initialize" finished-at="2021-10-05T22:40:37 EDT" duration-ms="3017" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method signature="getValidate()[pri:0, instance:framework.Validator@6b4a4e18]" started-at="2021-10-05T22:40:52 EDT" name="getValidate" finished-at="2021-10-05T22:40:52 EDT" duration-ms="174" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Rediff.com: News | Rediffmail | Stock Quotes | Shopping] but found [Rediff.com: News | Rediffmail | Stock Quotes | Shoppin]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Rediff.com: News | Rediffmail | Stock Quotes | Shopping] but found [Rediff.com: News | Rediffmail | Stock Quotes | Shoppin]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at framework.Validator.getValidate(Validator.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getValidate -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:framework.Validator@6b4a4e18]" started-at="2021-10-05T22:40:53 EDT" name="closeBrowser" finished-at="2021-10-05T22:40:53 EDT" duration-ms="132" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- framework.Validator -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
